apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: stockapp
type: Opaque
stringData:
  MYSQL_ROOT_PASSWORD: rootpassword
  MYSQL_DATABASE: stockdb
  MYSQL_USER: stockuser
  MYSQL_PASSWORD: stockpass
