apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: stockapp
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/mmasabalvi/stockapp-cloud-devops-pipeline.git
    targetRevision: main
    path: k8s

  destination:
    server: https://kubernetes.default.svc
    namespace: stockapp

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
